version: 2
jobs:
  build:
    docker:
      - image: cimg/node:8.17

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint JS
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test -- --maxWorkers=4



